services:
    database_service:
        class:        AppBundle\Service\DatabaseService
        arguments:    [%database_host%, %database_port%, %database_name%]
    cache_service:
        class:        AppBundle\Service\CacheService
        arguments:    [%cache_host%, %cache_port%, %cache_prefix%, %cache_password%]